// GENERATED by scripts/generate-builtin-plugins.mjs from friday.config.json. Do not edit manually.
import type { FridayPlugin } from "./plugin.js";
import capabilities from "../plugins/capabilities/index.js";
import agent from "../plugins/agent/index.js";
import alerts from "../plugins/alerts/index.js";
import artifacts from "../plugins/artifacts/index.js";
import audit from "../plugins/audit/index.js";
import auth from "../plugins/auth/index.js";
import autonomy from "../plugins/autonomy/index.js";
import channels from "../plugins/channels/index.js";
import compaction from "../plugins/compaction/index.js";
import conditionalHooks from "../plugins/conditional-hooks/index.js";
import evaluation from "../plugins/evaluation/index.js";
import diagnostics from "../plugins/diagnostics/index.js";
import events from "../plugins/events/index.js";
import execution from "../plugins/execution/index.js";
import generations from "../plugins/generations/index.js";
import hostDoctor from "../plugins/host-doctor/index.js";
import hostPrivileges from "../plugins/host-privileges/index.js";
import integrations from "../plugins/integrations/index.js";
import lifecycle from "../plugins/lifecycle/index.js";
import mcp from "../plugins/mcp/index.js";
import memory from "../plugins/memory/index.js";
import model from "../plugins/model/index.js";
import observability from "../plugins/observability/index.js";
import permissions from "../plugins/permissions/index.js";
import prompts from "../plugins/prompts/index.js";
import refinement from "../plugins/refinement/index.js";
import rlm from "../plugins/rlm/index.js";
import routing from "../plugins/routing/index.js";
import runtimeSettings from "../plugins/runtime-settings/index.js";
import sandbox from "../plugins/sandbox/index.js";
import scheduler from "../plugins/scheduler/index.js";
import spending from "../plugins/spending/index.js";
import selfImprovement from "../plugins/self-improvement/index.js";
import sessionResources from "../plugins/session-resources/index.js";
import sessionJobs from "../plugins/session-jobs/index.js";
import sessions from "../plugins/sessions/index.js";
import skills from "../plugins/skills/index.js";
import subagents from "../plugins/subagents/index.js";
import system from "../plugins/system/index.js";
import tools from "../plugins/tools/index.js";
import turnLoop from "../plugins/turn-loop/index.js";
import vault from "../plugins/vault/index.js";
import voice from "../plugins/voice/index.js";
import webhooks from "../plugins/webhooks/index.js";
import worktrees from "../plugins/worktrees/index.js";

/** Ordered exactly like friday.config.json; Map insertion order is startup order. */
export const BUILTIN_PLUGINS: ReadonlyMap<string, FridayPlugin> = new Map([
  ["./plugins/capabilities/index.ts", capabilities],
  ["./plugins/agent/index.ts", agent],
  ["./plugins/alerts/index.ts", alerts],
  ["./plugins/artifacts/index.ts", artifacts],
  ["./plugins/audit/index.ts", audit],
  ["./plugins/auth/index.ts", auth],
  ["./plugins/autonomy/index.ts", autonomy],
  ["./plugins/channels/index.ts", channels],
  ["./plugins/compaction/index.ts", compaction],
  ["./plugins/conditional-hooks/index.ts", conditionalHooks],
  ["./plugins/evaluation/index.ts", evaluation],
  ["./plugins/diagnostics/index.ts", diagnostics],
  ["./plugins/events/index.ts", events],
  ["./plugins/execution/index.ts", execution],
  ["./plugins/generations/index.ts", generations],
  ["./plugins/host-doctor/index.ts", hostDoctor],
  ["./plugins/host-privileges/index.ts", hostPrivileges],
  ["./plugins/integrations/index.ts", integrations],
  ["./plugins/lifecycle/index.ts", lifecycle],
  ["./plugins/mcp/index.ts", mcp],
  ["./plugins/memory/index.ts", memory],
  ["./plugins/model/index.ts", model],
  ["./plugins/observability/index.ts", observability],
  ["./plugins/permissions/index.ts", permissions],
  ["./plugins/prompts/index.ts", prompts],
  ["./plugins/refinement/index.ts", refinement],
  ["./plugins/rlm/index.ts", rlm],
  ["./plugins/routing/index.ts", routing],
  ["./plugins/runtime-settings/index.ts", runtimeSettings],
  ["./plugins/sandbox/index.ts", sandbox],
  ["./plugins/scheduler/index.ts", scheduler],
  ["./plugins/spending/index.ts", spending],
  ["./plugins/self-improvement/index.ts", selfImprovement],
  ["./plugins/session-resources/index.ts", sessionResources],
  ["./plugins/session-jobs/index.ts", sessionJobs],
  ["./plugins/sessions/index.ts", sessions],
  ["./plugins/skills/index.ts", skills],
  ["./plugins/subagents/index.ts", subagents],
  ["./plugins/system/index.ts", system],
  ["./plugins/tools/index.ts", tools],
  ["./plugins/turn-loop/index.ts", turnLoop],
  ["./plugins/vault/index.ts", vault],
  ["./plugins/voice/index.ts", voice],
  ["./plugins/webhooks/index.ts", webhooks],
  ["./plugins/worktrees/index.ts", worktrees],
]);
